/**
 * @file    alarm_task.h
 * @author  Sunil Sutar
 * @brief   Alarm Task interface.
 *
 * @details
 * Provides the interface for the event-driven Alarm Task.
 *
 * The Alarm Task receives fault and recovery notifications
 * from the Processing Task using FreeRTOS task notifications.
 *
 * Responsibilities:
 *      - Receive alarm notifications
 *      - Decode alarm bitmasks
 *      - Report active alarms
 *      - Report system recovery
 *
 * Communication:
 *      ProcessingTask -> Task Notification -> AlarmTask
 *
 * Health monitoring:
 *      AlarmActivity
 */

#ifndef ALARM_TASK_H
#define ALARM_TASK_H

#include "FreeRTOS.h"
#include "task.h"

/**
 * @brief Alarm handling task.
 *
 * Handles system alarms generated by abnormal
 * industrial sensor conditions.
 *
 * @param pvParameters Task parameter.
 */
void AlarmTask(void *pvParameters);

#endif /* ALARM_TASK_H */